<?php

/**
 * BaseArticleDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $article_option
 * @property Article $Article
 * 
 * @method integer       getArticleId()      Returns the current record's "article_id" value
 * @method string        getArticleOption()  Returns the current record's "article_option" value
 * @method Article       getArticle()        Returns the current record's "Article" value
 * @method ArticleDetail setArticleId()      Sets the current record's "article_id" value
 * @method ArticleDetail setArticleOption()  Sets the current record's "article_option" value
 * @method ArticleDetail setArticle()        Sets the current record's "Article" value
 * 
 * @package    sf14
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_detail');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('article_option', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}