<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $body
 * @property Article $Article
 * 
 * @method integer getArticleId()  Returns the current record's "article_id" value
 * @method string  getBody()       Returns the current record's "body" value
 * @method Article getArticle()    Returns the current record's "Article" value
 * @method Comment setArticleId()  Sets the current record's "article_id" value
 * @method Comment setBody()       Sets the current record's "body" value
 * @method Comment setArticle()    Sets the current record's "Article" value
 * 
 * @package    sf14
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('body', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}