<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/28 14:26:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf14',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
