<?php

/**
 * ArticleDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleDetail');
    }
}