homepage:
  url:    /
  param:  { module: Page, action: Show, slug: top }

page_show:
  url:    /page/:slug
  param:  { module: Page, action: Show }

news_list:
  url:    /news
  param:  { module: Page, action: NewsList }

news_show:
  url:    /news/:slug
  param:  { module: Page, action: NewsShow }

inquiry_new:
  url:    /inquiry/new
  param:  { module: Inquiry, action: New }

inquiry_complete:
  url:    /inquiry/complete
  param:  { module: Inquiry, action: Complete }

doctrine_show:
  url:    /doctrine
  param:  { module: Doctrine, action: Index }

doctrine_create:
  url:    /doctrine/create
  param:  { module: Doctrine, action: create }

doctrine_update:
  url:    /doctrine/update
  param:  { module: Doctrine, action: update }

doctrine_delete:
  url:    /doctrine/delete
  param:  { module: Doctrine, action: delete }

doctrine_find:
  url:    /doctrine/find
  param:  { module: Doctrine, action: find }

doctrine_doctrine_query:
  url:    /doctrine/doctrine_query
  param:  { module: Doctrine, action: DoctrineQuery }

