<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/30 15:12:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfonyband;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_unicode_ci',
  ),
  'name' => 'doctrine',
)),);
